use std::fmt;
use std::marker::PhantomData;
use std::ops::Not;

use crate::Value;
use crate::sql::Sql;

/// A column of model `M`.
///
/// `#[derive(Model)]` generates one associated constant per field, named
/// after the field in `SCREAMING_SNAKE_CASE` (`User::EMAIL`, `User::ID`, …).
/// Columns are tied to their model, so a `Post` column can't accidentally be
/// used to filter `User`s.
pub struct Column<M> {
    name: &'static str,
    _model: PhantomData<fn() -> M>,
}

impl<M> Column<M> {
    /// Create a column handle. Normally generated by `#[derive(Model)]`.
    pub const fn new(name: &'static str) -> Self {
        Self {
            name,
            _model: PhantomData,
        }
    }

    /// The column name in the database.
    pub const fn name(&self) -> &'static str {
        self.name
    }

    fn cmp(self, op: &'static str, value: impl Into<Value>) -> Expr<M> {
        Expr::new(Cond::Cmp {
            column: self.name,
            op,
            value: value.into(),
        })
    }

    /// `column = value`
    pub fn eq(self, value: impl Into<Value>) -> Expr<M> {
        self.cmp("=", value)
    }

    /// `column <> value`
    pub fn ne(self, value: impl Into<Value>) -> Expr<M> {
        self.cmp("<>", value)
    }

    /// `column > value`
    pub fn gt(self, value: impl Into<Value>) -> Expr<M> {
        self.cmp(">", value)
    }

    /// `column >= value`
    pub fn gte(self, value: impl Into<Value>) -> Expr<M> {
        self.cmp(">=", value)
    }

    /// `column < value`
    pub fn lt(self, value: impl Into<Value>) -> Expr<M> {
        self.cmp("<", value)
    }

    /// `column <= value`
    pub fn lte(self, value: impl Into<Value>) -> Expr<M> {
        self.cmp("<=", value)
    }

    /// `column LIKE pattern`
    pub fn like(self, pattern: impl Into<Value>) -> Expr<M> {
        self.cmp("LIKE", pattern)
    }

    /// `column NOT LIKE pattern`
    pub fn not_like(self, pattern: impl Into<Value>) -> Expr<M> {
        self.cmp("NOT LIKE", pattern)
    }

    /// Case-insensitive `column ILIKE pattern`
    pub fn ilike(self, pattern: impl Into<Value>) -> Expr<M> {
        self.cmp("ILIKE", pattern)
    }

    /// `column LIKE '%text%'`, escaping `%`, `_` and `\` in `text`.
    pub fn contains(self, text: &str) -> Expr<M> {
        self.like(format!("%{}%", escape_like(text)))
    }

    /// `column LIKE 'text%'`, escaping `%`, `_` and `\` in `text`.
    pub fn starts_with(self, text: &str) -> Expr<M> {
        self.like(format!("{}%", escape_like(text)))
    }

    /// `column LIKE '%text'`, escaping `%`, `_` and `\` in `text`.
    pub fn ends_with(self, text: &str) -> Expr<M> {
        self.like(format!("%{}", escape_like(text)))
    }

    /// `column IN (…)`. An empty list matches nothing.
    pub fn is_in<V: Into<Value>>(self, values: impl IntoIterator<Item = V>) -> Expr<M> {
        Expr::new(Cond::In {
            column: self.name,
            values: values.into_iter().map(Into::into).collect(),
            negated: false,
        })
    }

    /// `column NOT IN (…)`. An empty list matches everything.
    pub fn not_in<V: Into<Value>>(self, values: impl IntoIterator<Item = V>) -> Expr<M> {
        Expr::new(Cond::In {
            column: self.name,
            values: values.into_iter().map(Into::into).collect(),
            negated: true,
        })
    }

    /// `column BETWEEN low AND high`
    pub fn between(self, low: impl Into<Value>, high: impl Into<Value>) -> Expr<M> {
        Expr::new(Cond::Between {
            column: self.name,
            low: low.into(),
            high: high.into(),
        })
    }

    /// `column IS NULL`
    pub fn is_null(self) -> Expr<M> {
        Expr::new(Cond::Null {
            column: self.name,
            negated: false,
        })
    }

    /// `column IS NOT NULL`
    pub fn is_not_null(self) -> Expr<M> {
        Expr::new(Cond::Null {
            column: self.name,
            negated: true,
        })
    }

    /// Ascending ordering on this column.
    pub fn asc(self) -> Order<M> {
        Order::new(self.name, Direction::Asc)
    }

    /// Descending ordering on this column.
    pub fn desc(self) -> Order<M> {
        Order::new(self.name, Direction::Desc)
    }
}

impl<M> Clone for Column<M> {
    fn clone(&self) -> Self {
        *self
    }
}

impl<M> Copy for Column<M> {}

impl<M> fmt::Debug for Column<M> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_tuple("Column").field(&self.name).finish()
    }
}

impl<M> fmt::Display for Column<M> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.name)
    }
}

fn escape_like(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    for c in text.chars() {
        if matches!(c, '%' | '_' | '\\') {
            out.push('\\');
        }
        out.push(c);
    }
    out
}

/// A boolean condition on model `M`, used in `WHERE` clauses.
///
/// Combine conditions with [`Expr::and`], [`Expr::or`] and `!` (negation),
/// or build them from raw SQL with [`Expr::raw`].
pub struct Expr<M> {
    pub(crate) cond: Cond,
    _model: PhantomData<fn() -> M>,
}

impl<M> Expr<M> {
    fn new(cond: Cond) -> Self {
        Self {
            cond,
            _model: PhantomData,
        }
    }

    /// A raw SQL condition where each `?` is bound to the next parameter.
    ///
    /// ```ignore
    /// Expr::raw("lower(email) = lower(?)", ["Ann@Example.com"])
    /// ```
    pub fn raw<V: Into<Value>>(
        sql: impl Into<String>,
        params: impl IntoIterator<Item = V>,
    ) -> Self {
        Self::new(Cond::Raw {
            sql: sql.into(),
            params: params.into_iter().map(Into::into).collect(),
        })
    }

    /// A condition that is always true.
    pub fn all() -> Self {
        Self::new(Cond::And(Vec::new()))
    }

    /// A condition that is always false.
    pub fn none() -> Self {
        Self::new(Cond::Or(Vec::new()))
    }

    /// Both `self` and `other` must hold.
    pub fn and(self, other: Expr<M>) -> Self {
        Self::new(match self.cond {
            Cond::And(mut list) => {
                list.push(other.cond);
                Cond::And(list)
            }
            cond => Cond::And(vec![cond, other.cond]),
        })
    }

    /// Either `self` or `other` must hold.
    pub fn or(self, other: Expr<M>) -> Self {
        Self::new(match self.cond {
            Cond::Or(mut list) if !list.is_empty() => {
                list.push(other.cond);
                Cond::Or(list)
            }
            cond => Cond::Or(vec![cond, other.cond]),
        })
    }

    /// Every condition in `exprs` must hold (`TRUE` when empty).
    pub fn all_of(exprs: impl IntoIterator<Item = Expr<M>>) -> Self {
        Self::new(Cond::And(exprs.into_iter().map(|e| e.cond).collect()))
    }

    /// At least one condition in `exprs` must hold (`FALSE` when empty).
    pub fn any_of(exprs: impl IntoIterator<Item = Expr<M>>) -> Self {
        Self::new(Cond::Or(exprs.into_iter().map(|e| e.cond).collect()))
    }
}

impl<M> Not for Expr<M> {
    type Output = Expr<M>;

    fn not(self) -> Self::Output {
        Self::new(Cond::Not(Box::new(self.cond)))
    }
}

impl<M> Clone for Expr<M> {
    fn clone(&self) -> Self {
        Self::new(self.cond.clone())
    }
}

impl<M> fmt::Debug for Expr<M> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        self.cond.fmt(f)
    }
}

#[derive(Debug, Clone)]
pub(crate) enum Cond {
    Cmp {
        column: &'static str,
        op: &'static str,
        value: Value,
    },
    In {
        column: &'static str,
        values: Vec<Value>,
        negated: bool,
    },
    Between {
        column: &'static str,
        low: Value,
        high: Value,
    },
    Null {
        column: &'static str,
        negated: bool,
    },
    Raw {
        sql: String,
        params: Vec<Value>,
    },
    And(Vec<Cond>),
    Or(Vec<Cond>),
    Not(Box<Cond>),
}

impl Cond {
    pub(crate) fn write(&self, sql: &mut Sql) {
        match self {
            Cond::Cmp { column, op, value } => {
                sql.push_ident(column).push(" ").push(op).push(" ");
                sql.bind(value.clone());
            }
            Cond::In {
                column,
                values,
                negated,
            } => {
                if values.is_empty() {
                    sql.push(if *negated { "TRUE" } else { "FALSE" });
                    return;
                }
                sql.push_ident(column)
                    .push(if *negated { " NOT IN (" } else { " IN (" });
                sql.push_list(values, ", ", |sql, v| {
                    sql.bind(v.clone());
                });
                sql.push(")");
            }
            Cond::Between { column, low, high } => {
                sql.push_ident(column).push(" BETWEEN ");
                sql.bind(low.clone()).push(" AND ").bind(high.clone());
            }
            Cond::Null { column, negated } => {
                sql.push_ident(column)
                    .push(if *negated { " IS NOT NULL" } else { " IS NULL" });
            }
            Cond::Raw { sql: raw, params } => {
                sql.push("(").push_raw(raw, params).push(")");
            }
            Cond::And(list) => Self::write_group(sql, list, " AND ", "TRUE"),
            Cond::Or(list) => Self::write_group(sql, list, " OR ", "FALSE"),
            Cond::Not(inner) => {
                sql.push("NOT (");
                inner.write(sql);
                sql.push(")");
            }
        }
    }

    fn write_group(sql: &mut Sql, list: &[Cond], sep: &str, empty: &str) {
        match list {
            [] => {
                sql.push(empty);
            }
            [single] => single.write(sql),
            many => {
                sql.push("(");
                sql.push_list(many, sep, |sql, c| c.write(sql));
                sql.push(")");
            }
        }
    }
}

/// Sort direction for `ORDER BY`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Direction {
    /// Ascending (`ASC`).
    Asc,
    /// Descending (`DESC`).
    Desc,
}

/// An `ORDER BY` term on model `M`, created with [`Column::asc`] or [`Column::desc`].
pub struct Order<M> {
    pub(crate) column: &'static str,
    pub(crate) direction: Direction,
    pub(crate) nulls: Option<bool>,
    _model: PhantomData<fn() -> M>,
}

impl<M> Order<M> {
    fn new(column: &'static str, direction: Direction) -> Self {
        Self {
            column,
            direction,
            nulls: None,
            _model: PhantomData,
        }
    }

    /// Put `NULL`s first.
    pub fn nulls_first(mut self) -> Self {
        self.nulls = Some(true);
        self
    }

    /// Put `NULL`s last.
    pub fn nulls_last(mut self) -> Self {
        self.nulls = Some(false);
        self
    }

    pub(crate) fn write(&self, sql: &mut Sql) {
        sql.push_ident(self.column).push(match self.direction {
            Direction::Asc => " ASC",
            Direction::Desc => " DESC",
        });
        match self.nulls {
            Some(true) => sql.push(" NULLS FIRST"),
            Some(false) => sql.push(" NULLS LAST"),
            None => sql,
        };
    }
}

impl<M> Clone for Order<M> {
    fn clone(&self) -> Self {
        Self {
            column: self.column,
            direction: self.direction,
            nulls: self.nulls,
            _model: PhantomData,
        }
    }
}

impl<M> fmt::Debug for Order<M> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("Order")
            .field("column", &self.column)
            .field("direction", &self.direction)
            .field("nulls_first", &self.nulls)
            .finish()
    }
}

impl<M> From<Column<M>> for Order<M> {
    fn from(column: Column<M>) -> Self {
        column.asc()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    struct T;
    const A: Column<T> = Column::new("a");
    const B: Column<T> = Column::new("b");

    fn render(e: Expr<T>) -> String {
        let mut sql = Sql::new();
        e.cond.write(&mut sql);
        sql.as_str().to_owned()
    }

    #[test]
    fn renders_conditions() {
        assert_eq!(render(A.eq(1)), r#""a" = $1"#);
        assert_eq!(render(A.eq(1).and(B.gt(2))), r#"("a" = $1 AND "b" > $2)"#);
        assert_eq!(
            render(A.eq(1).or(B.is_null()).and(!A.is_in([1, 2]))),
            r#"(("a" = $1 OR "b" IS NULL) AND NOT ("a" IN ($2, $3)))"#
        );
        assert_eq!(render(A.is_in(Vec::<i32>::new())), "FALSE");
        assert_eq!(render(A.not_in(Vec::<i32>::new())), "TRUE");
        assert_eq!(render(A.between(1, 5)), r#""a" BETWEEN $1 AND $2"#);
        assert_eq!(render(Expr::all()), "TRUE");
        assert_eq!(render(Expr::any_of([])), "FALSE");
        assert_eq!(render(Expr::raw("lower(a) = ?", ["x"])), "(lower(a) = $1)");
    }

    #[test]
    fn escapes_like_patterns() {
        let mut sql = Sql::new();
        A.contains("50%_off").cond.write(&mut sql);
        assert_eq!(sql.params()[0], Value::from(r"%50\%\_off%"));
    }
}
