// @generated by rok-db-gen. Do not edit: change the .sql files and run `rok-db-gen generate`.
/// Revert the latest `steps` applied migrations, newest first. Returns the
/// versions reverted.
pub async fn down(db: &rok_db::Db, steps: usize) -> rok_db::Result<Vec<i64>> {
    rok_db::migration::revert(db, crate::migrations::MIGRATIONS, steps).await
}
