// @generated by rok-db-gen. Do not edit: change the .sql files and run `rok-db-gen generate`.
//! Database code generated by rok-db-gen from `db/*.sql`: one module
//! per file with its models, enums and queries, and the migrations.
//!
//! Apply pending migrations with [`up`] and revert them with [`down`].
#![allow(clippy::all, clippy::pedantic, clippy::nursery)]
#[rustfmt::skip]
mod down;
#[rustfmt::skip]
pub mod migrations;
#[rustfmt::skip]
pub mod plan;
#[rustfmt::skip]
pub mod post;
#[rustfmt::skip]
pub mod types;
#[rustfmt::skip]
mod up;
#[rustfmt::skip]
pub mod user;
pub use down::down;
pub use up::up;
