// @generated by rok-db-gen. Do not edit: change the .sql files and run `rok-db-gen generate`.
//! Every migration, oldest first. Each one is a pair of files in
//! `migrations/`; never edit a migration that was applied somewhere.
/// Every migration, oldest first.
pub const MIGRATIONS: &[rok_db::migration::Migration] = &[
    rok_db::migration::Migration {
        version: 1,
        name: "init",
        up: include_str!("../migrations/0001_init.up.sql"),
        down: include_str!("../migrations/0001_init.down.sql"),
    },
];
