// @generated by rok-db-gen. Do not edit: change the .sql files and run `rok-db-gen generate`.
//! Generated from `db/plan.sql`.
/// A subscription plan.
#[derive(Debug, Clone, PartialEq, rok_db::Model)]
#[rok(table = "plans")]
pub struct Plan {
    /// `id` (BIGSERIAL NOT NULL).
    #[rok(primary_key, generated)]
    pub id: i64,
    /// `name` (TEXT NOT NULL).
    pub name: String,
    /// Exact money: NUMERIC becomes rust_decimal's Decimal (feature `decimal`).
    pub price: rok_db::sqlx::types::Decimal,
    /// How often it bills: INTERVAL becomes PgInterval.
    pub period: rok_db::sqlx::postgres::types::PgInterval,
    /// `trial` (INTERVAL).
    pub trial: Option<rok_db::sqlx::postgres::types::PgInterval>,
}
/// `-- name: create_plan :one!` from `db/plan.sql:13`:
///
/// ```sql
/// INSERT INTO plans (name, price, period) VALUES ($1, $2, $3) RETURNING *
/// ```
pub async fn create_plan<'e>(
    db: impl rok_db::Executor<'e>,
    name: &str,
    price: rok_db::sqlx::types::Decimal,
    period: rok_db::sqlx::postgres::types::PgInterval,
) -> rok_db::Result<crate::plan::Plan> {
    rok_db::raw(
            r#"INSERT INTO plans (name, price, period) VALUES ($1, $2, $3) RETURNING *"#,
        )
        .bind(name)
        .bind(price)
        .bind(period)
        .invalidates("plans")
        .fetch_one(db)
        .await
}
/// `-- name: cheaper_than :many` from `db/plan.sql:16`:
///
/// ```sql
/// SELECT * FROM plans WHERE price < $1 ORDER BY price, id
/// ```
pub async fn cheaper_than<'e>(
    db: impl rok_db::Executor<'e>,
    price: rok_db::sqlx::types::Decimal,
) -> rok_db::Result<Vec<crate::plan::Plan>> {
    rok_db::raw(r#"SELECT * FROM plans WHERE price < $1 ORDER BY price, id"#)
        .bind(price)
        .fetch_all(db)
        .await
}
