// @generated by rok-db-gen. Do not edit: change the .sql files and run `rok-db-gen generate`.
//! Generated from `db/post.sql`.
/// Something a user wrote.
#[derive(Debug, Clone, PartialEq, rok_db::Model)]
#[rok(table = "posts")]
pub struct Post {
    /// `id` (BIGSERIAL NOT NULL).
    #[rok(primary_key, generated)]
    pub id: i64,
    /// `author_id` (BIGINT NOT NULL).
    #[rok(belongs_to(author = crate::user::User))]
    pub author_id: i64,
    /// `title` (TEXT NOT NULL).
    pub title: String,
    /// `body` (TEXT NOT NULL DEFAULT '').
    pub body: String,
    /// `tags` (TEXT[] NOT NULL DEFAULT '{}').
    pub tags: Vec<String>,
    /// `views` (INTEGER NOT NULL DEFAULT 0).
    pub views: i32,
    /// `published_at` (TIMESTAMPTZ).
    pub published_at: Option<
        rok_db::sqlx::types::chrono::DateTime<rok_db::sqlx::types::chrono::Utc>,
    >,
}
/// `-- name: create_post :one!` from `db/post.sql:15`:
///
/// ```sql
/// INSERT INTO posts (author_id, title, tags) VALUES ($1, $2, $3) RETURNING *
/// ```
pub async fn create_post<'e>(
    db: impl rok_db::Executor<'e>,
    author_id: i64,
    title: &str,
    tags: &[String],
) -> rok_db::Result<crate::post::Post> {
    rok_db::raw(
            r#"INSERT INTO posts (author_id, title, tags) VALUES ($1, $2, $3) RETURNING *"#,
        )
        .bind(author_id)
        .bind(title)
        .bind(tags)
        .invalidates("posts")
        .fetch_one(db)
        .await
}
/// `-- name: top_for_author :many` from `db/post.sql:18`:
///
/// ```sql
/// SELECT * FROM posts WHERE author_id = $1 ORDER BY views DESC, id LIMIT $2
/// ```
pub async fn top_for_author<'e>(
    db: impl rok_db::Executor<'e>,
    author_id: i64,
    limit: i64,
) -> rok_db::Result<Vec<crate::post::Post>> {
    rok_db::raw(
            r#"SELECT * FROM posts WHERE author_id = $1 ORDER BY views DESC, id LIMIT $2"#,
        )
        .bind(author_id)
        .bind(limit)
        .fetch_all(db)
        .await
}
/// A row returned by [`feed`].
#[derive(Debug, Clone, PartialEq, rok_db::FromRow)]
pub struct FeedRow {
    /// The `id` column.
    pub id: i64,
    /// The `title` column.
    pub title: String,
    /// The `author_email` column.
    pub author_email: String,
}
/// Titles with their author's email, newest first.
///
/// `-- name: feed :stream` from `db/post.sql:22`:
///
/// ```sql
/// SELECT p.id, p.title, u.email AS author_email
/// FROM posts p
/// JOIN users u ON u.id = p.author_id
/// WHERE p.published_at IS NOT NULL AND u.deleted_at IS NULL
/// ORDER BY p.published_at DESC
/// ```
pub fn feed<'e>(
    db: impl rok_db::Executor<'e> + 'e,
) -> rok_db::BoxStream<'e, rok_db::Result<FeedRow>> {
    rok_db::raw(
            r#"SELECT p.id, p.title, u.email AS author_email
FROM posts p
JOIN users u ON u.id = p.author_id
WHERE p.published_at IS NOT NULL AND u.deleted_at IS NULL
ORDER BY p.published_at DESC"#,
        )
        .stream(db)
}
/// `-- name: add_view :exec` from `db/post.sql:29`:
///
/// ```sql
/// UPDATE posts SET views = views + 1 WHERE id = $1
/// ```
pub async fn add_view<'e>(
    db: impl rok_db::Executor<'e>,
    id: i64,
) -> rok_db::Result<u64> {
    rok_db::raw(r#"UPDATE posts SET views = views + 1 WHERE id = $1"#)
        .bind(id)
        .invalidates("posts")
        .execute(db)
        .await
}
