// @generated by rok-db-gen. Do not edit: change the .sql files and run `rok-db-gen generate`.
//! Generated from `db/_types.sql`.
/// Who may do what.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, rok_db::DbEnum)]
#[rok(type_name = "user_role")]
pub enum UserRole {
    /// `admin`
    #[rok(rename = "admin")]
    Admin,
    /// `editor`
    #[rok(rename = "editor")]
    Editor,
    /// `member`
    #[rok(rename = "member")]
    Member,
}
