// @generated by rok-db-gen. Do not edit: change the .sql files and run `rok-db-gen generate`.
/// Apply every pending migration, oldest first, each in its own transaction.
/// Returns the versions applied.
pub async fn up(db: &rok_db::Db) -> rok_db::Result<Vec<i64>> {
    rok_db::migration::apply(db, crate::migrations::MIGRATIONS).await
}
