// @generated by rok-db-gen. Do not edit: change the .sql files and run `rok-db-gen generate`.
//! Generated from `db/user.sql`.
/// A person who can sign in.
#[derive(Debug, Clone, PartialEq, rok_db::Model)]
#[rok(
    table = "users",
    timestamps,
    soft_delete,
    has_many(posts = crate::post::Post::AUTHOR_ID)
)]
pub struct User {
    /// `id` (BIGSERIAL NOT NULL).
    #[rok(primary_key, generated)]
    pub id: i64,
    /// Unique, compared case-insensitively by the queries below.
    pub email: String,
    /// `name` (TEXT).
    pub name: Option<String>,
    /// `role` (user_role NOT NULL DEFAULT 'member').
    pub role: crate::types::UserRole,
    /// `created_at` (TIMESTAMPTZ NOT NULL DEFAULT now()).
    pub created_at: rok_db::sqlx::types::chrono::DateTime<
        rok_db::sqlx::types::chrono::Utc,
    >,
    /// `updated_at` (TIMESTAMPTZ NOT NULL DEFAULT now()).
    pub updated_at: rok_db::sqlx::types::chrono::DateTime<
        rok_db::sqlx::types::chrono::Utc,
    >,
    /// `deleted_at` (TIMESTAMPTZ).
    pub deleted_at: Option<
        rok_db::sqlx::types::chrono::DateTime<rok_db::sqlx::types::chrono::Utc>,
    >,
}
/// `-- name: find_by_email :one` from `db/user.sql:16`:
///
/// ```sql
/// SELECT * FROM users WHERE lower(email) = lower($1) AND deleted_at IS NULL
/// ```
pub async fn find_by_email<'e>(
    db: impl rok_db::Executor<'e>,
    email: &str,
) -> rok_db::Result<Option<crate::user::User>> {
    rok_db::raw(
            r#"SELECT * FROM users WHERE lower(email) = lower($1) AND deleted_at IS NULL"#,
        )
        .bind(email)
        .fetch_optional(db)
        .await
}
/// A row returned by [`count_by_role`].
#[derive(Debug, Clone, PartialEq, rok_db::FromRow)]
pub struct CountByRoleRow {
    /// The `role` column.
    pub role: crate::types::UserRole,
    /// The `total!` column.
    #[rok(column = "total!")]
    pub total: i64,
}
/// How many active users have each role.
///
/// `-- name: count_by_role :many` from `db/user.sql:20`:
///
/// ```sql
/// SELECT role, count(*) AS "total!"
/// FROM users
/// WHERE deleted_at IS NULL
/// GROUP BY role
/// ORDER BY role
/// ```
pub async fn count_by_role<'e>(
    db: impl rok_db::Executor<'e>,
) -> rok_db::Result<Vec<CountByRoleRow>> {
    rok_db::raw(
            r#"SELECT role, count(*) AS "total!"
FROM users
WHERE deleted_at IS NULL
GROUP BY role
ORDER BY role"#,
        )
        .fetch_all(db)
        .await
}
/// `-- name: emails :many` from `db/user.sql:27`:
///
/// ```sql
/// SELECT email FROM users WHERE deleted_at IS NULL ORDER BY email
/// ```
pub async fn emails<'e>(db: impl rok_db::Executor<'e>) -> rok_db::Result<Vec<String>> {
    rok_db::raw(r#"SELECT email FROM users WHERE deleted_at IS NULL ORDER BY email"#)
        .fetch_all::<(String,), _>(db)
        .await
        .map(|rows| rows.into_iter().map(|(value,)| value).collect())
}
/// `-- name: promote :exec` from `db/user.sql:30`:
///
/// ```sql
/// UPDATE users SET role = 'admin', updated_at = now() WHERE id = $1
/// ```
pub async fn promote<'e>(db: impl rok_db::Executor<'e>, id: i64) -> rok_db::Result<u64> {
    rok_db::raw(r#"UPDATE users SET role = 'admin', updated_at = now() WHERE id = $1"#)
        .bind(id)
        .invalidates("users")
        .execute(db)
        .await
}
